### PR TITLE
Add popup-isearch-yank.

### PR DESCRIPTION
**Pull request by kostafey**
Add popup-isearch-yank.

### CODE REVIEW

**Comment by kostafey** [comment]
Looks like test environment problem. Is it possible to fix?

**Comment by syohex** [comment]
> Is it possible to fix?

Yes, it is newer Cask issue. I'll fix it later.

**Comment by syohex** [comment]
Thanks PR. I have cherry-picked your commit and fixed CI issue. However I use only `C-y` key binding because `C-v` is not emacs like key binding.

**Comment by kostafey** [comment]
Why not `C-v`? There is no conflict here. Users can use both. One likes `C-y`, other prefer `cua-mode` and `C-v`.
Ok, it's possible to add it to `popup-isearch-keymap` in custom's `.emacs` but I can't see any reason to avoid it by default.

**Comment by syohex** [comment]
I want to save key bindings as possible in the future and it is enough to assign one key binding.

**Pull request closed without merging**
