### PR TITLE
Pass filtering function as an argument to popup-menu*

### PR DESCRIPTION
**Pull request by ancane**
Hi. I was trying to use fuzzy matching inside a popup menu and only way I could do it was defadvice'ing `popup-isearch-filter-list` function. Instead I lifter it to parameters of `popup-menu*` so that I could use it with custom filtering function. Please, let me know if there is another way or, please, consider this PR. Thank yon in advance.

### CODE REVIEW

**Comment by syohex** [comment]
Looks good.

**Comment by ancane** [comment]
@syohex Thank you!

**Comment by ancane** [comment]
Hi, @syohex. Looks like 0.5.3 is stable enough to have new tag at stable melpa. Could you please, push a new tag?

**Comment by syohex** [comment]
Done

https://github.com/auto-complete/popup-el/releases/tag/v0.5.3

**Comment by ancane** [comment]
Many thanks.

**Pull request merged**
